services:
  web:
    build: . # Fait référence au Dockerfile pour créer une première image
    ports:
      - "8000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_DEBUG: "true"
  redis:
    image: "redis:alpine" # Crée une deuxième image ?